### ISSUE TITLE
override smilies array?

### ISSUE THREAD

**Issue by pursual** [mistic100/angular-smilies#10]
How do you override the array of smilies that is hardcoded in the JS?

**Comment by mistic100** [comment]
Read the Building section of the readme.

**Comment by pursual** [comment]
I meant more at runtime, as I am using the bower package. Thanks though.

**Comment by mistic100** [comment]
Actually it was really designed to be as simple as possible, and at this time I was a real noob in Angular.

You can submit a PR with a service provider for configuration, I will be happy to integrate it.
