### ISSUE TITLE
How to add new smilies and emojis 

### ISSUE THREAD

**Issue by gvkweb** [mistic100/angular-smilies#15]
I want to add more smiles and emojis please tell me

**Comment by mistic100** [comment]
Did you read the README ?

Put images in `src/smilies` and run `grunt`

**Comment by gvkweb** [comment]
Thanks for your reply., But I am new to angular js and grunt i don't know how to build  really. Please give some more info is any chance to add manually  if available please tell

**Comment by mistic100** [comment]
It is written !!!
```
npm install
grunt
```

nothing more

----

If you want to add it manually, edit the files :

- angular-smilies.png
- angular-smilies.css
- angular-smilies.js

It's a standard CSS Sprite and the `smilies` variable line 11 is the full list of names.
