### ISSUE TITLE
Angular UI popover template

### ISSUE THREAD

**Issue by Devqon** [mistic100/angular-smilies#4]
Angular UI popover nowadays supports templates and urls, though the popover with smilies still doesn't work.

**Comment by mistic100** [comment]
PR to support the main Augular UI repo are welcomed :)

**Comment by Christian-Schiffer** [comment]
I am having problems with using angular UI too, the smiles did not even show until I added display: inline-flex; to the css. Now the smiles work fine using the similes directive but the popover as Devqon said does not.

Any idea's on what I can do other than changing to the mgcrea.ngStrap framework?
