### ISSUE TITLE
focusOnChange has no effect

### ISSUE THREAD

**Issue by hohl** [mistic100/angular-smilies#6]
Seems like `focusOnChange` doesn't have any effect, not on my app, nor on your demo page. Using Google Chrome. (My is build on latest AngularJS 1.4 branch if this information matters.)

**Comment by mistic100** [comment]
is it better now ?

**Comment by hohl** [comment]
better :+1: 

Thanks!

**Comment by hohl** [comment]
No, I'm wrong. Just used the non-minified version now. It looks like it works as long as I use the non-minified version, but it stops working when using the minified one.
