### ISSUE TITLE
angular-sanitize linky

### ISSUE THREAD

**Issue by hohl** [mistic100/angular-smilies#7]
I'd like to use your smiles filter in combination with Angulars linky. At first this seems to work, used like the following:

    message.body | linky | smilies

However it crashes `$sanitize` when links (or parts of the HTML tags) are replaced with smilies. A very common case is when linky tries to convert "support@mail.com" to "mailto:support@mail.com" (since :s is replaced by a smiley).

Is there any chance to get both of them working together?

**Comment by mistic100** [comment]
Apply smilies before linky ?

**Comment by hohl** [comment]
that won't work since `linky` will validate that there are no HTML tags in the string (which could be harmful in case of user content brought to other users - like in a chat app)

**Comment by mistic100** [comment]
you can see here that I don't apply word boudaries on the regex https://github.com/mistic100/angular-smilies/blob/master/src/angular-smilies.js#L21

I did this because it's not uncommon to type `:):):):):)` which would be half parsed with `\b`.

However you can change it for your needs

**Comment by mistic100** [comment]
With the new service provider you can configure the parser to always use word boundaries

``` js
smiliesParserProvider.alwaysUseBoundaries(true);
```

it will not replace ":s" in "mailto:support@mail.com"
